# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-Merge
version:      0.08
version_from: Merge.pm
installdirs:  site
requires:
    Algorithm::Diff:               1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
